# -*- coding: utf-8 -*-
"""numpy_tutorial1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1leGrolGzCuU_vjOw10zCPIUdFJq2sn56
"""

import numpy as np

list2=[1,2,3]
print(list2)
type(list2)

np_array=np.array([])
print(np_array)
type(np_array)

a= np.array([1,2,3])
print(a)

a.shape

b=np.array([(1,2,3),(5,6,7)])
print(b)
type(b)

b.shape

c=np.array([(1,2,3),(5,6,7)],dtype=float)
print(c)

x=np.zeros((4,5))
print(x)

y=np.ones((3,3))
print(y)

z=np.full((5,3),2)
print(z)

a=np.eye(3)
print(a)

b=np.random.random((2,4))
print(b)

c=np.random.randint(10,100,(3,5))
print(c)

#array of evenly spaced values-specifying the number of values required
d=np.linspace(10,100,10)
print(d)

e=np.arange(10,30,2)   #array of evenly spaced values-#specifying the step
print(e)

#convert the list into numpy
list2=[1,2,3,4,5,6]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

c=np.random.randint(10,100,(3,5))
print(c)

print(c.shape)

print(c.shape)

print(c.shape[0])

list1=[1,2]
list2=[5,6]
print(list1+list2)

a=np.random.randint(0,10,(6,2))
b=np.random.randint(10,20,(6,2))
print(a)
print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

#array mapipulation
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

trans=np.transpose(array)#transpose
print(trans)
print(trans.shape)

trans2=array.T
print(trans2)
print(trans2.shape)

#creating arrays
# you can create array from python lists using np.array
import numpy as np
#creating a 10 array
array_1d=np.array([1,2,3,4,5,6,7,8,9,10])
print(array_1d)
array2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2d)

#array slicing
#you can slice array to acces specific parts of them
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9])
#slicing
print("first 5 elemnts:",array[:5])
print("last 4 elements:",array[-4:])
print("elements from index 2 to 6:",array[2:7])

# you can change the shape ofd an array using reshaping
import numpy as np
array=np.array([1,2,3,4,5,6,7,7,8,9])
#reshape to 2x5 array
reshaped_array=array.reshape(2,5)
print(reshaped_array)

array = np.array([1,2,3,4,5])
#mean
print("mean:",np.mean(array))
print("standard deviation:",np.std(array))
#sum
print("sum:",np.sum(array))
#cumulative sum
print("cumulative sum:",np.cumsum(array))
#array of zeros
ones_array =np.ones((2,4))
print("array of ones:\n",ones_array)
#identity matrix
identity_matrix=np.eye(3)
print("identity matrix:\n",identity_matrix)

